

export const ScreensName = {
  SplashScreen: 'SplashScreen',
  AppStartScreen: 'AppStartScreen',
  Login: 'Login',
  exporeFintechScreen: 'EXPLORE FINTECH HUB',
  welcomeToFintech: 'WELCOME TO FINTECH SAUDI',
  newPasswordScreen: 'newPasswordScreen',
  privateOfficeScreenOne: 'Private office',
  privateOfficeScreenTwo: 'PRIVATE OFFICE2',
  privateOfficeScreenThree: 'privateOfficeScreenThree',
  requestSentScreen: 'Request Sent',
  dedicatedDeskRequestSentScreen: 'DEDICATED DESK REQUEST SENT',
  summaryScreen: 'Summary',
  HomeScreen: 'HomeScreen',
  waitingScreen: 'waitingScreen',
  experimentalSummaryScreen: 'SUMMAR',
  MeetingHomeScreen: 'meetingwelcomescreen',
  bookMeetingRoom: 'Book Meeting Room ',
  meetingWhatsHappeningScreen: "What's happening",
  Meetingscreen: 'MEETING SCREEN',
  Meetingsummary: 'SUMMARY',
  Banktransferscreen: 'BANK TRANSFER',
  mainMenuScreen: 'MAIN MENU',
  HelpDeskScreen: 'Help Desk',
  reportproblemscreen: 'Report a problem',
  settingScreen: 'Settings',
  NotificationScreen: 'Notification Settings',
  AccessKeyScreen: 'Access Key',
  NotificationListScreen: 'Notifications',
  Profiledetail: 'Profile',
  Profiledetaileditscreen: 'Edit Profile',
  UpdatePasswordScreen: 'UPDATE PASSWORD',
  filterPackages: 'FILTER PACKAGES',
  MembershipDetails: 'MEMBERSHIP DETAILS',
  ChangePlan: 'Edit Plan Request',
  TeamCreditsScreen: 'Team Credits',
  dedicatedDeskScreenOne: 'Dedicated Desks',
  dedicatedDeskScreenTwo: 'Dedicated Desks 2',
  dedicatedDeskSummaryScreen: 'DedicatedDeskSummaryScreen',
  hybridScreen: 'Hybrid',
  hybridScreenOne: 'Hybrid Screen One',
  hybridScreenTwo: 'Hybrid Screen Two',
  hybridScreenThree: 'Hybrid Screen Three ',
  hybridScreenFour: 'Hybrid Screen Four',
  hybridSummaryScreen: 'Hybrid Summary Screen',
  hybridRequestSentScreen: 'Hybrid Request Sent Screen',
  invitationScreen: 'Invitations',
  bookingConfirmed: 'Confirmed',
  scheduledMeetingScreen: 'Scheduled Meetings',
  rescheduleMeeting: 'Meetings',
  webview: 'webview',
  changePasswordScreen: 'Change Password',
  updatePassword: 'UpdatePassword',
  requestPending:'Request Pending',
  dayPass:'Day Pass',
  dayPassSummary:'day pass Summary',
  dayPassPayment:'Payment',
  dayPassRequestSent:'dayPassRequestSent',
  dayPassHomeScreen:'dayPassHomeScreen',
  membershipInactive:'membershipInactive',
  myTeam:'My Team',
  addMembers:'Add Members',
  teamMemberDetail:'Team member details',
  AnnouncementScreen:'Announcement',
  DummyScreen:'Dummy',
  ReportSummaryScreen: 'ReportSummary',
  InvoiceSummaryScreen: 'MemoSummary',
  InvoiceDetailScreen: 'MemoDetail',
  ReviewPendingScreen: 'ReviewPending',
  TransactionDetailScreen: 'Transaction Detail',
  AddCreditScreen: 'Add Credit',
  PurchaseCreditScreen: 'Purchase Credit',
  yourPurchases:'Your Purchases',
  rescheduleDayPass:'Day Pass Summary',
  rescheduleDayPassMeeting:'Meeting Room Summary',
  invoiceDayPass:'Memo details',
  DeleteAccountScreenOne:'Manage Account & Data',
  DeleteAccountScreenTwo:'Delete Account & Data',
  DeleteAccountScreenThree:'Confirm Delete to Account',
  QRCodeScreen:'QRCode',
  FaqScreen:'FaqScreen',
  FaqDetailScreen:'FaqDetailScreen',
};