require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
#  use_modular_headers!
platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false


target 'FintechHub' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()


  pod 'Firebase', :modular_headers => true
  # pod 'Firebase/CoreOnly', '10.7.0'
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'BEMCheckBox',:modular_headers => true
  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'
  pod 'TouchID', :path => "../node_modules/react-native-touch-id"
  pod 'FirebaseCoreExtension', :modular_headers => true
pod 'FirebaseInstallations', :modular_headers => true
pod 'GoogleDataTransport', :modular_headers => true
pod 'nanopb', :modular_headers => true
  # pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'
  # pod 'React/Core', :path => '../node_modules/react-native'
  $RNFirebaseAsStaticFramework = true
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'FintechHubTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
